plugins {
    id 'com.android.application'
}

android {
    namespace 'com.h4xtor.share'
    compileSdk 36

    defaultConfig {
        applicationId 'com.h4xtor.share'
        minSdk 29
        targetSdk 36
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
